-- =========================================
-- SCRIPT PARA POPULAR BANCO COM DADOS DE TESTE
-- =========================================

-- 1. INSERIR NÍVEIS (20 níveis diversos)
INSERT INTO niveis (nivel, "createdAt", "updatedAt") VALUES
('Estagiário', NOW(), NOW()),
('Trainee', NOW(), NOW()),
('Júnior Frontend', NOW(), NOW()),
('Júnior Backend', NOW(), NOW()),
('Júnior Mobile', NOW(), NOW()),
('Pleno Frontend', NOW(), NOW()),
('Pleno Backend', NOW(), NOW()),
('Pleno Mobile', NOW(), NOW()),
('Pleno Fullstack', NOW(), NOW()),
('Sênior Frontend', NOW(), NOW()),
('Sênior Backend', NOW(), NOW()),
('Sênior Mobile', NOW(), NOW()),
('Sênior Fullstack', NOW(), NOW()),
('Tech Lead', NOW(), NOW()),
('Arquiteto de Software', NOW(), NOW()),
('Principal Engineer', NOW(), NOW()),
('Staff Engineer', NOW(), NOW()),
('Engineering Manager', NOW(), NOW()),
('CTO', NOW(), NOW()),
('Consultor Especialista', NOW(), NOW());

-- 2. INSERIR DESENVOLVEDORES (100 desenvolvedores)
INSERT INTO desenvolvedores (nivel_id, nome, sexo, data_nascimento, hobby, "createdAt", "updatedAt") VALUES
-- Estagiários e Trainees
(1, 'Ana Silva Santos', 'F', '2002-03-15', 'Leitura e programação', NOW(), NOW()),
(1, 'Carlos Eduardo Lima', 'M', '2001-07-22', 'Gaming e tecnologia', NOW(), NOW()),
(2, 'Maria Fernanda Costa', 'F', '2000-11-08', 'Dança e desenvolvimento web', NOW(), NOW()),
(2, 'João Pedro Oliveira', 'M', '2001-05-14', 'Futebol e aplicativos mobile', NOW(), NOW()),
(1, 'Beatriz Almeida', 'F', '2002-09-03', 'Fotografia e design', NOW(), NOW()),

-- Júniores
(3, 'Lucas Gabriel Ferreira', 'M', '1999-01-20', 'Ciclismo e React', NOW(), NOW()),
(3, 'Isabela Rodrigues', 'F', '1998-12-11', 'Yoga e Vue.js', NOW(), NOW()),
(4, 'Rafael Mendes Silva', 'M', '1999-08-05', 'Música e Node.js', NOW(), NOW()),
(4, 'Camila Souza Santos', 'F', '1998-04-18', 'Culinária e Python', NOW(), NOW()),
(5, 'Diego Barbosa Lima', 'M', '1999-10-27', 'Basquete e Flutter', NOW(), NOW()),
(5, 'Letícia Cardoso', 'F', '1998-06-09', 'Natação e React Native', NOW(), NOW()),
(3, 'Gustavo Henrique Dias', 'M', '1999-03-12', 'Violão e JavaScript', NOW(), NOW()),
(4, 'Júlia Martins Rocha', 'F', '1998-11-25', 'Teatro e Java', NOW(), NOW()),
(5, 'Matheus Costa Pereira', 'M', '1999-07-08', 'Skate e Kotlin', NOW(), NOW()),
(3, 'Larissa Fernandes', 'F', '1998-02-14', 'Pintura e CSS', NOW(), NOW()),

-- Plenos
(6, 'Bruno Alves Machado', 'M', '1995-05-30', 'Corrida e Angular', NOW(), NOW()),
(6, 'Fernanda Gomes Silva', 'F', '1994-09-17', 'Escalada e TypeScript', NOW(), NOW()),
(7, 'André Luiz Santos', 'M', '1995-12-04', 'Xadrez e .NET', NOW(), NOW()),
(7, 'Priscila Oliveira Costa', 'F', '1994-08-21', 'Jardinagem e Django', NOW(), NOW()),
(8, 'Thiago Ribeiro Lima', 'M', '1995-01-15', 'Surfe e Swift', NOW(), NOW()),
(8, 'Caroline Pereira Santos', 'F', '1994-06-28', 'Pilates e iOS Development', NOW(), NOW()),
(9, 'Ricardo Silva Nunes', 'M', '1995-11-10', 'Motociclismo e DevOps', NOW(), NOW()),
(9, 'Vanessa Carvalho', 'F', '1994-04-03', 'Meditação e Full Stack', NOW(), NOW()),
(6, 'Felipe Augusto Dias', 'M', '1995-07-19', 'Pescaria e Vue.js', NOW(), NOW()),
(7, 'Tatiana Souza Lima', 'F', '1994-10-12', 'Dança e Ruby on Rails', NOW(), NOW()),
(8, 'Rodrigo Fernandes', 'M', '1995-03-25', 'Tênis e Android', NOW(), NOW()),
(9, 'Débora Machado Silva', 'F', '1994-12-08', 'Leitura e Microservices', NOW(), NOW()),

-- Sêniores
(10, 'Leonardo Castro Rocha', 'M', '1990-02-14', 'Vinhedo e React Expert', NOW(), NOW()),
(10, 'Alessandra Lima Santos', 'F', '1989-11-28', 'Gastronomia e UX/UI', NOW(), NOW()),
(11, 'Fábio Henrique Costa', 'M', '1991-06-07', 'Cervejaria artesanal e Microservices', NOW(), NOW()),
(11, 'Renata Oliveira Silva', 'F', '1990-09-22', 'Astronomia e Cloud Computing', NOW(), NOW()),
(12, 'Marcos Vinícius Lima', 'M', '1989-12-16', 'Mergulho e Mobile Architecture', NOW(), NOW()),
(12, 'Adriana Ferreira Costa', 'F', '1991-03-05', 'Alpinismo e Flutter Expert', NOW(), NOW()),
(13, 'Paulo Roberto Santos', 'M', '1990-08-11', 'Marcenaria e System Design', NOW(), NOW()),
(13, 'Cristina Almeida Silva', 'F', '1989-05-24', 'Fotografia profissional e Tech Lead', NOW(), NOW()),
(10, 'Gabriel Augusto Dias', 'M', '1991-01-09', 'Trilha e Frontend Architecture', NOW(), NOW()),
(11, 'Patrícia Souza Lima', 'F', '1990-07-18', 'Yoga e Backend Specialist', NOW(), NOW()),

-- Tech Leads e Arquitetos
(14, 'Alexandre Silva Pereira', 'M', '1987-04-12', 'Vinicultura e Team Leadership', NOW(), NOW()),
(14, 'Luciana Costa Rodrigues', 'F', '1986-10-29', 'Arte contemporânea e Agile Coach', NOW(), NOW()),
(15, 'Sergio Luiz Fernandes', 'M', '1988-01-20', 'Aviação e System Architecture', NOW(), NOW()),
(15, 'Monica Alves Santos', 'F', '1987-08-15', 'Opera e Software Architecture', NOW(), NOW()),
(16, 'Roberto Carlos Silva', 'M', '1985-11-03', 'Automobilismo e Principal Engineering', NOW(), NOW()),
(16, 'Eliane Souza Costa', 'F', '1986-06-17', 'Equitação e Technical Strategy', NOW(), NOW()),
(14, 'Daniel Augusto Lima', 'M', '1988-09-08', 'Culinária japonesa e Engineering Management', NOW(), NOW()),
(15, 'Simone Ferreira Dias', 'F', '1987-02-25', 'Dança de salão e Enterprise Architecture', NOW(), NOW()),

-- Especialistas e Liderança
(17, 'Eduardo Henrique Santos', 'M', '1984-12-14', 'Colecionismo e Staff Engineering', NOW(), NOW()),
(17, 'Carla Regina Oliveira', 'F', '1983-07-31', 'Teatro musical e Technical Excellence', NOW(), NOW()),
(18, 'Fernando Silva Costa', 'M', '1982-05-08', 'Navegação e Engineering Management', NOW(), NOW()),
(18, 'Isabel Cristina Lima', 'F', '1983-11-22', 'Literatura e People Management', NOW(), NOW()),
(19, 'Antonio Carlos Dias', 'M', '1980-03-17', 'Enologia e Technology Strategy', NOW(), NOW()),
(19, 'Sandra Lucia Santos', 'F', '1981-09-04', 'Arqueologia e CTO Vision', NOW(), NOW()),
(20, 'Marcelo Augusto Silva', 'M', '1979-06-26', 'Filosofia e Technical Consulting', NOW(), NOW()),
(20, 'Vera Lucia Costa', 'F', '1980-12-13', 'Botânica e Enterprise Consulting', NOW(), NOW()),

-- Mais desenvolvedores para completar 100
(3, 'Pedro Henrique Alves', 'M', '1999-04-11', 'Podcast e HTML/CSS', NOW(), NOW()),
(4, 'Aline Santos Ferreira', 'F', '1998-08-07', 'Bordado e PHP', NOW(), NOW()),
(5, 'Vinícius Lima Costa', 'M', '1999-12-19', 'Boxe e Xamarin', NOW(), NOW()),
(6, 'Natália Rodrigues Silva', 'F', '1995-02-28', 'Cerâmica e Sass', NOW(), NOW()),
(7, 'Igor Pereira Santos', 'M', '1994-10-15', 'Parkour e Spring Boot', NOW(), NOW()),
(8, 'Sabrina Costa Lima', 'F', '1995-06-02', 'Karatê e Ionic', NOW(), NOW()),
(9, 'Henrique Silva Dias', 'M', '1994-11-24', 'Escalada indoor e GraphQL', NOW(), NOW()),
(10, 'Mariana Alves Costa', 'F', '1991-01-13', 'Stand-up comedy e Redux', NOW(), NOW()),
(11, 'Leandro Santos Silva', 'M', '1990-05-06', 'Astrofotografia e Elasticsearch', NOW(), NOW()),
(12, 'Bruna Ferreira Lima', 'F', '1989-09-18', 'Cosplay e Unity', NOW(), NOW()),
(6, 'César Augusto Dias', 'M', '1995-07-29', 'Quadrinhos e Webpack', NOW(), NOW()),
(7, 'Elisa Souza Santos', 'F', '1994-03-11', 'Origami e Laravel', NOW(), NOW()),
(8, 'Otávio Lima Silva', 'M', '1995-11-05', 'Cubo mágico e React Native', NOW(), NOW()),
(9, 'Raquel Costa Alves', 'F', '1994-01-27', 'Aquarela e Docker', NOW(), NOW()),
(10, 'Samuel Pereira Lima', 'M', '1991-08-14', 'Bonsai e Kubernetes', NOW(), NOW()),
(3, 'Jéssica Silva Santos', 'F', '1998-12-03', 'Ballet e Bootstrap', NOW(), NOW()),
(4, 'Murilo Costa Ferreira', 'M', '1999-06-16', 'Capoeira e CodeIgniter', NOW(), NOW()),
(5, 'Paloma Alves Lima', 'F', '1998-10-09', 'Ukulele e Cordova', NOW(), NOW()),
(6, 'Renan Santos Silva', 'M', '1995-04-22', 'Rubik cube e Jest', NOW(), NOW()),
(7, 'Tânia Lima Costa', 'F', '1994-08-05', 'Tricô e Express.js', NOW(), NOW()),
(11, 'Washington Silva Santos', 'M', '1990-12-17', 'Aquarismo e MongoDB', NOW(), NOW()),
(12, 'Yara Costa Lima', 'F', '1989-07-30', 'Ikebana e Firebase', NOW(), NOW()),
(13, 'Zeca Ferreira Silva', 'M', '1991-03-23', 'Barbershop e AWS', NOW(), NOW()),
(10, 'Amanda Souza Costa', 'F', '1990-11-06', 'Crochê e Next.js', NOW(), NOW()),
(11, 'Benedito Lima Santos', 'M', '1989-09-19', 'Dominó e Nest.js', NOW(), NOW()),
(12, 'Cláudia Silva Ferreira', 'F', '1991-05-12', 'Pilates e Gatsby', NOW(), NOW()),
(13, 'Davi Costa Lima', 'M', '1990-01-25', 'Xadrez online e Nuxt.js', NOW(), NOW()),
(6, 'Evelyn Santos Silva', 'F', '1995-07-08', 'Crossfit e Tailwind', NOW(), NOW()),
(7, 'Francisco Lima Costa', 'M', '1994-11-21', 'Pesca esportiva e Material-UI', NOW(), NOW()),
(8, 'Graziela Silva Santos', 'F', '1995-03-14', 'Artesanato e Styled Components', NOW(), NOW()),
(9, 'Hélio Costa Ferreira', 'M', '1994-09-27', 'Astronomia amadora e Redux Toolkit', NOW(), NOW()),
(10, 'Ingrid Lima Silva', 'F', '1991-06-10', 'Jardinagem urbana e Zustand', NOW(), NOW()),
(11, 'Jorge Santos Costa', 'M', '1990-02-23', 'Motociclismo vintage e Prisma', NOW(), NOW()),
(3, 'Karina Silva Lima', 'F', '1999-08-16', 'K-pop dance e Semantic UI', NOW(), NOW()),
(4, 'Luciano Costa Santos', 'M', '1998-12-29', 'Café specialty e Chakra UI', NOW(), NOW()),
(5, 'Melissa Lima Silva', 'F', '1999-04-02', 'Pole dance e Ant Design', NOW(), NOW()),
(6, 'Nicolas Santos Costa', 'M', '1995-10-15', 'Beatbox e Material Design', NOW(), NOW()),
(7, 'Olívia Silva Lima', 'F', '1994-06-28', 'Scrapbook e Bulma CSS', NOW(), NOW()),
(8, 'Patrick Costa Santos', 'M', '1995-02-11', 'Skateboard vintage e Foundation CSS', NOW(), NOW()),
(9, 'Quintina Lima Silva', 'F', '1994-08-24', 'Aquarela botânica e Pure CSS', NOW(), NOW()),
(10, 'Roberto Silva Costa', 'M', '1991-04-07', 'Cerveja artesanal e Spectre CSS', NOW(), NOW()),
(11, 'Silvana Costa Lima', 'F', '1990-12-20', 'Orquídeas e Milligram CSS', NOW(), NOW()),
(12, 'Tadeu Lima Santos', 'M', '1989-08-03', 'Radioamadorismo e Tachyons CSS', NOW(), NOW()),
(13, 'Úrsula Santos Silva', 'F', '1991-10-16', 'Feng shui e Skeleton CSS', NOW(), NOW()),
(6, 'Vinícius Silva Costa', 'M', '1995-06-29', 'Parkour urbano e Picnic CSS', NOW(), NOW()),
(7, 'Wanda Costa Santos', 'F', '1994-04-12', 'Tai chi chuan e Mustard UI', NOW(), NOW()),
(8, 'Xavier Santos Lima', 'M', '1995-12-25', 'Origami modular e Paper CSS', NOW(), NOW()),
(9, 'Yasmin Lima Costa', 'F', '1994-10-08', 'Dança árabe e Materialize CSS', NOW(), NOW()),
(14, 'Zuleika Silva Santos', 'F', '1987-05-21', 'Caligrafia japonesa e Leadership', NOW(), NOW());